import re

extra_themes = """
"Tokyo Night": {
Name:          "Tokyo Night",
Primary:       lipgloss.Color("#7aa2f7"),
Secondary:     lipgloss.Color("#f7768e"),
Tertiary:      lipgloss.Color("#9ece6a"),
BgBase:        lipgloss.Color("#1a1b26"),
BgBaseLighter: lipgloss.Color("#24283b"),
BgSubtle:      lipgloss.Color("#414868"),
BgOverlay:     lipgloss.Color("#565f89"),
FgBase:        lipgloss.Color("#c0caf5"),
FgMuted:       lipgloss.Color("#a9b1d6"),
FgHalfMuted:   lipgloss.Color("#9aa5ce"),
FgSubtle:      lipgloss.Color("#565f89"),
Border:        lipgloss.Color("#414868"),
BorderFocus:   lipgloss.Color("#7aa2f7"),
Error:         lipgloss.Color("#f7768e"),
Warning:       lipgloss.Color("#e0af68"),
Info:          lipgloss.Color("#7dcfff"),
White:         lipgloss.Color("#c0caf5"),
BlueLight:     lipgloss.Color("#7dcfff"),
Blue:          lipgloss.Color("#7aa2f7"),
BlueDark:      lipgloss.Color("#3d59a1"),
Yellow:        lipgloss.Color("#e0af68"),
GreenLight:    lipgloss.Color("#9ece6a"),
Green:         lipgloss.Color("#73daca"),
GreenDark:     lipgloss.Color("#41a6b5"),
Red:           lipgloss.Color("#f7768e"),
RedDark:       lipgloss.Color("#db4b4b"),
},
"Gruvbox Dark": {
Name:          "Gruvbox Dark",
Primary:       lipgloss.Color("#d3869b"),
Secondary:     lipgloss.Color("#fabd2f"),
Tertiary:      lipgloss.Color("#8ec07c"),
BgBase:        lipgloss.Color("#282828"),
BgBaseLighter: lipgloss.Color("#3c3836"),
BgSubtle:      lipgloss.Color("#504945"),
BgOverlay:     lipgloss.Color("#665c54"),
FgBase:        lipgloss.Color("#ebdbb2"),
FgMuted:       lipgloss.Color("#d5c4a1"),
FgHalfMuted:   lipgloss.Color("#bdae93"),
FgSubtle:      lipgloss.Color("#a89984"),
Border:        lipgloss.Color("#504945"),
BorderFocus:   lipgloss.Color("#d3869b"),
Error:         lipgloss.Color("#fb4934"),
Warning:       lipgloss.Color("#fabd2f"),
Info:          lipgloss.Color("#83a598"),
White:         lipgloss.Color("#fbf1c7"),
BlueLight:     lipgloss.Color("#83a598"),
Blue:          lipgloss.Color("#458588"),
BlueDark:      lipgloss.Color("#076678"),
Yellow:        lipgloss.Color("#fabd2f"),
GreenLight:    lipgloss.Color("#8ec07c"),
Green:         lipgloss.Color("#b8bb26"),
GreenDark:     lipgloss.Color("#98971a"),
Red:           lipgloss.Color("#fb4934"),
RedDark:       lipgloss.Color("#cc241d"),
},
"Nord": {
Name:          "Nord",
Primary:       lipgloss.Color("#88c0d0"),
Secondary:     lipgloss.Color("#b48ead"),
Tertiary:      lipgloss.Color("#81a1c1"),
BgBase:        lipgloss.Color("#2e3440"),
BgBaseLighter: lipgloss.Color("#3b4252"),
BgSubtle:      lipgloss.Color("#434c5e"),
BgOverlay:     lipgloss.Color("#4c566a"),
FgBase:        lipgloss.Color("#eceff4"),
FgMuted:       lipgloss.Color("#e5e9f0"),
FgHalfMuted:   lipgloss.Color("#d8dee9"),
FgSubtle:      lipgloss.Color("#4c566a"),
Border:        lipgloss.Color("#434c5e"),
BorderFocus:   lipgloss.Color("#88c0d0"),
Error:         lipgloss.Color("#bf616a"),
Warning:       lipgloss.Color("#ebcb8b"),
Info:          lipgloss.Color("#81a1c1"),
White:         lipgloss.Color("#ffffff"),
BlueLight:     lipgloss.Color("#88c0d0"),
Blue:          lipgloss.Color("#81a1c1"),
BlueDark:      lipgloss.Color("#5e81ac"),
Yellow:        lipgloss.Color("#ebcb8b"),
GreenLight:    lipgloss.Color("#a3be8c"),
Green:         lipgloss.Color("#a3be8c"),
GreenDark:     lipgloss.Color("#a3be8c"),
Red:           lipgloss.Color("#bf616a"),
RedDark:       lipgloss.Color("#bf616a"),
},
"Solarized Dark": {
Name:          "Solarized Dark",
Primary:       lipgloss.Color("#268bd2"),
Secondary:     lipgloss.Color("#cb4b16"),
Tertiary:      lipgloss.Color("#2aa198"),
BgBase:        lipgloss.Color("#002b36"),
BgBaseLighter: lipgloss.Color("#073642"),
BgSubtle:      lipgloss.Color("#586e75"),
BgOverlay:     lipgloss.Color("#657b83"),
FgBase:        lipgloss.Color("#839496"),
FgMuted:       lipgloss.Color("#93a1a1"),
FgHalfMuted:   lipgloss.Color("#eee8d5"),
FgSubtle:      lipgloss.Color("#586e75"),
Border:        lipgloss.Color("#586e75"),
BorderFocus:   lipgloss.Color("#268bd2"),
Error:         lipgloss.Color("#dc322f"),
Warning:       lipgloss.Color("#b58900"),
Info:          lipgloss.Color("#268bd2"),
White:         lipgloss.Color("#fdf6e3"),
BlueLight:     lipgloss.Color("#268bd2"),
Blue:          lipgloss.Color("#268bd2"),
BlueDark:      lipgloss.Color("#268bd2"),
Yellow:        lipgloss.Color("#b58900"),
GreenLight:    lipgloss.Color("#859900"),
Green:         lipgloss.Color("#859900"),
GreenDark:     lipgloss.Color("#859900"),
Red:           lipgloss.Color("#dc322f"),
RedDark:       lipgloss.Color("#dc322f"),
},
"""

with open("internal/ui/styles/theme.go", "r") as f:
    content = f.read()

# Insert extra themes before the closing brace of the Themes map
content = content.replace('}\n\n// GetTheme', extra_themes + '}\n\n// GetTheme')

with open("internal/ui/styles/theme.go", "w") as f:
    f.write(content)
