package styles

import (
	"sort"

	"charm.land/lipgloss/v2"
	"image/color"
)

type Theme struct {
	Name          string
	IsLight       bool // true for light themes (inverts some UI assumptions)
	Primary       color.Color
	Secondary     color.Color
	Tertiary      color.Color
	BgBase        color.Color
	BgBaseLighter color.Color
	BgSubtle      color.Color
	BgOverlay     color.Color
	FgBase        color.Color
	FgMuted       color.Color
	FgHalfMuted   color.Color
	FgSubtle      color.Color
	Border        color.Color
	BorderFocus   color.Color
	Error         color.Color
	Warning       color.Color
	Info          color.Color
	White         color.Color
	BlueLight     color.Color
	Blue          color.Color
	BlueDark      color.Color
	Yellow        color.Color
	GreenLight    color.Color
	Green         color.Color
	GreenDark     color.Color
	Red           color.Color
	RedDark       color.Color
}

var Themes = map[string]Theme{
	"Catppuccin Mocha": {
		Name:          "Catppuccin Mocha",
		Primary:       lipgloss.Color("#cba6f7"),
		Secondary:     lipgloss.Color("#f38ba8"),
		Tertiary:      lipgloss.Color("#89b4fa"),
		BgBase:        lipgloss.Color("#1e1e2e"),
		BgBaseLighter: lipgloss.Color("#313244"),
		BgSubtle:      lipgloss.Color("#45475a"),
		BgOverlay:     lipgloss.Color("#585b70"),
		FgBase:        lipgloss.Color("#cdd6f4"),
		FgMuted:       lipgloss.Color("#bac2de"),
		FgHalfMuted:   lipgloss.Color("#a6adc8"),
		FgSubtle:      lipgloss.Color("#9399b2"),
		Border:        lipgloss.Color("#45475a"),
		BorderFocus:   lipgloss.Color("#cba6f7"),
		Error:         lipgloss.Color("#f38ba8"),
		Warning:       lipgloss.Color("#f9e2af"),
		Info:          lipgloss.Color("#89b4fa"),
		White:         lipgloss.Color("#cdd6f4"),
		BlueLight:     lipgloss.Color("#89b4fa"),
		Blue:          lipgloss.Color("#89b4fa"),
		BlueDark:      lipgloss.Color("#89b4fa"),
		Yellow:        lipgloss.Color("#f9e2af"),
		GreenLight:    lipgloss.Color("#a6e3a1"),
		Green:         lipgloss.Color("#a6e3a1"),
		GreenDark:     lipgloss.Color("#a6e3a1"),
		Red:           lipgloss.Color("#f38ba8"),
		RedDark:       lipgloss.Color("#f38ba8"),
	},
	"Catppuccin Latte": {
		Name:          "Catppuccin Latte",
		IsLight:       true,
		Primary:       lipgloss.Color("#8839ef"),
		Secondary:     lipgloss.Color("#d20f39"),
		Tertiary:      lipgloss.Color("#1e66f5"),
		BgBase:        lipgloss.Color("#eff1f5"),
		BgBaseLighter: lipgloss.Color("#e6e9ef"),
		BgSubtle:      lipgloss.Color("#ccd0da"),
		BgOverlay:     lipgloss.Color("#bcc0cc"),
		FgBase:        lipgloss.Color("#4c4f69"),
		FgMuted:       lipgloss.Color("#5c5f77"),
		FgHalfMuted:   lipgloss.Color("#6c6f85"),
		FgSubtle:      lipgloss.Color("#9ca0b0"),
		Border:        lipgloss.Color("#ccd0da"),
		BorderFocus:   lipgloss.Color("#8839ef"),
		Error:         lipgloss.Color("#d20f39"),
		Warning:       lipgloss.Color("#df8e1d"),
		Info:          lipgloss.Color("#1e66f5"),
		White:         lipgloss.Color("#4c4f69"),
		BlueLight:     lipgloss.Color("#209fb5"),
		Blue:          lipgloss.Color("#1e66f5"),
		BlueDark:      lipgloss.Color("#7287fd"),
		Yellow:        lipgloss.Color("#df8e1d"),
		GreenLight:    lipgloss.Color("#40a02b"),
		Green:         lipgloss.Color("#40a02b"),
		GreenDark:     lipgloss.Color("#179299"),
		Red:           lipgloss.Color("#d20f39"),
		RedDark:       lipgloss.Color("#e64553"),
	},
	"Dracula": {
		Name:          "Dracula",
		Primary:       lipgloss.Color("#bd93f9"),
		Secondary:     lipgloss.Color("#ff79c6"),
		Tertiary:      lipgloss.Color("#8be9fd"),
		BgBase:        lipgloss.Color("#282a36"),
		BgBaseLighter: lipgloss.Color("#44475a"),
		BgSubtle:      lipgloss.Color("#6272a4"),
		BgOverlay:     lipgloss.Color("#6272a4"),
		FgBase:        lipgloss.Color("#f8f8f2"),
		FgMuted:       lipgloss.Color("#bfbfbf"),
		FgHalfMuted:   lipgloss.Color("#999999"),
		FgSubtle:      lipgloss.Color("#6272a4"),
		Border:        lipgloss.Color("#44475a"),
		BorderFocus:   lipgloss.Color("#bd93f9"),
		Error:         lipgloss.Color("#ff5555"),
		Warning:       lipgloss.Color("#f1fa8c"),
		Info:          lipgloss.Color("#8be9fd"),
		White:         lipgloss.Color("#ffffff"),
		BlueLight:     lipgloss.Color("#8be9fd"),
		Blue:          lipgloss.Color("#8be9fd"),
		BlueDark:      lipgloss.Color("#6272a4"),
		Yellow:        lipgloss.Color("#f1fa8c"),
		GreenLight:    lipgloss.Color("#50fa7b"),
		Green:         lipgloss.Color("#50fa7b"),
		GreenDark:     lipgloss.Color("#50fa7b"),
		Red:           lipgloss.Color("#ff5555"),
		RedDark:       lipgloss.Color("#ff5555"),
	},
	"Default": {
		Name:          "Default",
		Primary:       lipgloss.Color("#9d80ff"),
		Secondary:     lipgloss.Color("#ff9900"),
		Tertiary:      lipgloss.Color("#00ffb7"),
		BgBase:        lipgloss.Color("#1f1f1f"),
		BgBaseLighter: lipgloss.Color("#2f2f2f"),
		BgSubtle:      lipgloss.Color("#3e3e3e"),
		BgOverlay:     lipgloss.Color("#4f4f4f"),
		FgBase:        lipgloss.Color("#e6e6e6"),
		FgMuted:       lipgloss.Color("#b3b3b3"),
		FgHalfMuted:   lipgloss.Color("#999999"),
		FgSubtle:      lipgloss.Color("#808080"),
		Border:        lipgloss.Color("#3e3e3e"),
		BorderFocus:   lipgloss.Color("#9d80ff"),
		Error:         lipgloss.Color("#ff2a2a"),
		Warning:       lipgloss.Color("#ff9900"),
		Info:          lipgloss.Color("#00d5ff"),
		White:         lipgloss.Color("#ffffff"),
		BlueLight:     lipgloss.Color("#00eeff"),
		Blue:          lipgloss.Color("#00d5ff"),
		BlueDark:      lipgloss.Color("#0088cc"),
		Yellow:        lipgloss.Color("#ffcc00"),
		GreenLight:    lipgloss.Color("#00ffb7"),
		Green:         lipgloss.Color("#00cc88"),
		GreenDark:     lipgloss.Color("#009955"),
		Red:           lipgloss.Color("#ff6666"),
		RedDark:       lipgloss.Color("#cc2a2a"),
	},
	"GitHub Dark": {
		Name:          "GitHub Dark",
		Primary:       lipgloss.Color("#58a6ff"),
		Secondary:     lipgloss.Color("#f78166"),
		Tertiary:      lipgloss.Color("#3fb950"),
		BgBase:        lipgloss.Color("#0d1117"),
		BgBaseLighter: lipgloss.Color("#161b22"),
		BgSubtle:      lipgloss.Color("#21262d"),
		BgOverlay:     lipgloss.Color("#30363d"),
		FgBase:        lipgloss.Color("#e6edf3"),
		FgMuted:       lipgloss.Color("#c9d1d9"),
		FgHalfMuted:   lipgloss.Color("#8b949e"),
		FgSubtle:      lipgloss.Color("#6e7681"),
		Border:        lipgloss.Color("#30363d"),
		BorderFocus:   lipgloss.Color("#58a6ff"),
		Error:         lipgloss.Color("#f85149"),
		Warning:       lipgloss.Color("#d29922"),
		Info:          lipgloss.Color("#58a6ff"),
		White:         lipgloss.Color("#f0f6fc"),
		BlueLight:     lipgloss.Color("#79c0ff"),
		Blue:          lipgloss.Color("#58a6ff"),
		BlueDark:      lipgloss.Color("#388bfd"),
		Yellow:        lipgloss.Color("#d29922"),
		GreenLight:    lipgloss.Color("#56d364"),
		Green:         lipgloss.Color("#3fb950"),
		GreenDark:     lipgloss.Color("#238636"),
		Red:           lipgloss.Color("#f85149"),
		RedDark:       lipgloss.Color("#da3633"),
	},
	"Kanagawa": {
		Name:          "Kanagawa",
		Primary:       lipgloss.Color("#7e9cd8"),
		Secondary:     lipgloss.Color("#ff5d62"),
		Tertiary:      lipgloss.Color("#7aa89f"),
		BgBase:        lipgloss.Color("#1f1f28"),
		BgBaseLighter: lipgloss.Color("#2a2a37"),
		BgSubtle:      lipgloss.Color("#363646"),
		BgOverlay:     lipgloss.Color("#54546d"),
		FgBase:        lipgloss.Color("#dcd7ba"),
		FgMuted:       lipgloss.Color("#c8c093"),
		FgHalfMuted:   lipgloss.Color("#a6a69c"),
		FgSubtle:      lipgloss.Color("#727169"),
		Border:        lipgloss.Color("#363646"),
		BorderFocus:   lipgloss.Color("#7e9cd8"),
		Error:         lipgloss.Color("#e82424"),
		Warning:       lipgloss.Color("#e6c384"),
		Info:          lipgloss.Color("#7fb4ca"),
		White:         lipgloss.Color("#dcd7ba"),
		BlueLight:     lipgloss.Color("#7fb4ca"),
		Blue:          lipgloss.Color("#7e9cd8"),
		BlueDark:      lipgloss.Color("#223249"),
		Yellow:        lipgloss.Color("#e6c384"),
		GreenLight:    lipgloss.Color("#98bb6c"),
		Green:         lipgloss.Color("#76946a"),
		GreenDark:     lipgloss.Color("#5a7a62"),
		Red:           lipgloss.Color("#ff5d62"),
		RedDark:       lipgloss.Color("#c34043"),
	},
	"Monokai Pro": {
		Name:          "Monokai Pro",
		Primary:       lipgloss.Color("#a9dc76"),
		Secondary:     lipgloss.Color("#ff6188"),
		Tertiary:      lipgloss.Color("#78dce8"),
		BgBase:        lipgloss.Color("#2d2a2e"),
		BgBaseLighter: lipgloss.Color("#403e41"),
		BgSubtle:      lipgloss.Color("#5b595c"),
		BgOverlay:     lipgloss.Color("#727072"),
		FgBase:        lipgloss.Color("#fcfcfa"),
		FgMuted:       lipgloss.Color("#c1c0c0"),
		FgHalfMuted:   lipgloss.Color("#939293"),
		FgSubtle:      lipgloss.Color("#727072"),
		Border:        lipgloss.Color("#5b595c"),
		BorderFocus:   lipgloss.Color("#a9dc76"),
		Error:         lipgloss.Color("#ff6188"),
		Warning:       lipgloss.Color("#ffd866"),
		Info:          lipgloss.Color("#78dce8"),
		White:         lipgloss.Color("#fcfcfa"),
		BlueLight:     lipgloss.Color("#78dce8"),
		Blue:          lipgloss.Color("#78dce8"),
		BlueDark:      lipgloss.Color("#5b595c"),
		Yellow:        lipgloss.Color("#ffd866"),
		GreenLight:    lipgloss.Color("#a9dc76"),
		Green:         lipgloss.Color("#a9dc76"),
		GreenDark:     lipgloss.Color("#7aac52"),
		Red:           lipgloss.Color("#ff6188"),
		RedDark:       lipgloss.Color("#cc4466"),
	},
	"One Dark Pro": {
		Name:          "One Dark Pro",
		Primary:       lipgloss.Color("#61afef"),
		Secondary:     lipgloss.Color("#e06c75"),
		Tertiary:      lipgloss.Color("#98c379"),
		BgBase:        lipgloss.Color("#282c34"),
		BgBaseLighter: lipgloss.Color("#2c313a"),
		BgSubtle:      lipgloss.Color("#3e4452"),
		BgOverlay:     lipgloss.Color("#4b5263"),
		FgBase:        lipgloss.Color("#abb2bf"),
		FgMuted:       lipgloss.Color("#8b92a0"),
		FgHalfMuted:   lipgloss.Color("#7f848e"),
		FgSubtle:      lipgloss.Color("#5c6370"),
		Border:        lipgloss.Color("#3e4452"),
		BorderFocus:   lipgloss.Color("#61afef"),
		Error:         lipgloss.Color("#e06c75"),
		Warning:       lipgloss.Color("#e5c07b"),
		Info:          lipgloss.Color("#61afef"),
		White:         lipgloss.Color("#dcdfe4"),
		BlueLight:     lipgloss.Color("#61afef"),
		Blue:          lipgloss.Color("#61afef"),
		BlueDark:      lipgloss.Color("#528bcc"),
		Yellow:        lipgloss.Color("#e5c07b"),
		GreenLight:    lipgloss.Color("#98c379"),
		Green:         lipgloss.Color("#98c379"),
		GreenDark:     lipgloss.Color("#7a9f60"),
		Red:           lipgloss.Color("#e06c75"),
		RedDark:       lipgloss.Color("#be5046"),
	},
	"Rosé Pine": {
		Name:          "Rosé Pine",
		Primary:       lipgloss.Color("#c4a7e7"),
		Secondary:     lipgloss.Color("#ebbcba"),
		Tertiary:      lipgloss.Color("#9ccfd8"),
		BgBase:        lipgloss.Color("#191724"),
		BgBaseLighter: lipgloss.Color("#1f1d2e"),
		BgSubtle:      lipgloss.Color("#26233a"),
		BgOverlay:     lipgloss.Color("#393552"),
		FgBase:        lipgloss.Color("#e0def4"),
		FgMuted:       lipgloss.Color("#908caa"),
		FgHalfMuted:   lipgloss.Color("#6e6a86"),
		FgSubtle:      lipgloss.Color("#524f67"),
		Border:        lipgloss.Color("#26233a"),
		BorderFocus:   lipgloss.Color("#c4a7e7"),
		Error:         lipgloss.Color("#eb6f92"),
		Warning:       lipgloss.Color("#f6c177"),
		Info:          lipgloss.Color("#9ccfd8"),
		White:         lipgloss.Color("#e0def4"),
		BlueLight:     lipgloss.Color("#9ccfd8"),
		Blue:          lipgloss.Color("#31748f"),
		BlueDark:      lipgloss.Color("#286983"),
		Yellow:        lipgloss.Color("#f6c177"),
		GreenLight:    lipgloss.Color("#9ccfd8"),
		Green:         lipgloss.Color("#31748f"),
		GreenDark:     lipgloss.Color("#286983"),
		Red:           lipgloss.Color("#eb6f92"),
		RedDark:       lipgloss.Color("#b4637a"),
	},
	"Tokyo Night": {
		Name:          "Tokyo Night",
		Primary:       lipgloss.Color("#7aa2f7"),
		Secondary:     lipgloss.Color("#f7768e"),
		Tertiary:      lipgloss.Color("#9ece6a"),
		BgBase:        lipgloss.Color("#1a1b26"),
		BgBaseLighter: lipgloss.Color("#24283b"),
		BgSubtle:      lipgloss.Color("#414868"),
		BgOverlay:     lipgloss.Color("#565f89"),
		FgBase:        lipgloss.Color("#c0caf5"),
		FgMuted:       lipgloss.Color("#a9b1d6"),
		FgHalfMuted:   lipgloss.Color("#9aa5ce"),
		FgSubtle:      lipgloss.Color("#565f89"),
		Border:        lipgloss.Color("#414868"),
		BorderFocus:   lipgloss.Color("#7aa2f7"),
		Error:         lipgloss.Color("#f7768e"),
		Warning:       lipgloss.Color("#e0af68"),
		Info:          lipgloss.Color("#7dcfff"),
		White:         lipgloss.Color("#c0caf5"),
		BlueLight:     lipgloss.Color("#7dcfff"),
		Blue:          lipgloss.Color("#7aa2f7"),
		BlueDark:      lipgloss.Color("#3d59a1"),
		Yellow:        lipgloss.Color("#e0af68"),
		GreenLight:    lipgloss.Color("#9ece6a"),
		Green:         lipgloss.Color("#73daca"),
		GreenDark:     lipgloss.Color("#41a6b5"),
		Red:           lipgloss.Color("#f7768e"),
		RedDark:       lipgloss.Color("#db4b4b"),
	},
	"Gruvbox Dark": {
		Name:          "Gruvbox Dark",
		Primary:       lipgloss.Color("#d3869b"),
		Secondary:     lipgloss.Color("#fabd2f"),
		Tertiary:      lipgloss.Color("#8ec07c"),
		BgBase:        lipgloss.Color("#282828"),
		BgBaseLighter: lipgloss.Color("#3c3836"),
		BgSubtle:      lipgloss.Color("#504945"),
		BgOverlay:     lipgloss.Color("#665c54"),
		FgBase:        lipgloss.Color("#ebdbb2"),
		FgMuted:       lipgloss.Color("#d5c4a1"),
		FgHalfMuted:   lipgloss.Color("#bdae93"),
		FgSubtle:      lipgloss.Color("#a89984"),
		Border:        lipgloss.Color("#504945"),
		BorderFocus:   lipgloss.Color("#d3869b"),
		Error:         lipgloss.Color("#fb4934"),
		Warning:       lipgloss.Color("#fabd2f"),
		Info:          lipgloss.Color("#83a598"),
		White:         lipgloss.Color("#fbf1c7"),
		BlueLight:     lipgloss.Color("#83a598"),
		Blue:          lipgloss.Color("#458588"),
		BlueDark:      lipgloss.Color("#076678"),
		Yellow:        lipgloss.Color("#fabd2f"),
		GreenLight:    lipgloss.Color("#8ec07c"),
		Green:         lipgloss.Color("#b8bb26"),
		GreenDark:     lipgloss.Color("#98971a"),
		Red:           lipgloss.Color("#fb4934"),
		RedDark:       lipgloss.Color("#cc241d"),
	},
	"Nord": {
		Name:          "Nord",
		Primary:       lipgloss.Color("#88c0d0"),
		Secondary:     lipgloss.Color("#b48ead"),
		Tertiary:      lipgloss.Color("#81a1c1"),
		BgBase:        lipgloss.Color("#2e3440"),
		BgBaseLighter: lipgloss.Color("#3b4252"),
		BgSubtle:      lipgloss.Color("#434c5e"),
		BgOverlay:     lipgloss.Color("#4c566a"),
		FgBase:        lipgloss.Color("#eceff4"),
		FgMuted:       lipgloss.Color("#e5e9f0"),
		FgHalfMuted:   lipgloss.Color("#d8dee9"),
		FgSubtle:      lipgloss.Color("#4c566a"),
		Border:        lipgloss.Color("#434c5e"),
		BorderFocus:   lipgloss.Color("#88c0d0"),
		Error:         lipgloss.Color("#bf616a"),
		Warning:       lipgloss.Color("#ebcb8b"),
		Info:          lipgloss.Color("#81a1c1"),
		White:         lipgloss.Color("#ffffff"),
		BlueLight:     lipgloss.Color("#88c0d0"),
		Blue:          lipgloss.Color("#81a1c1"),
		BlueDark:      lipgloss.Color("#5e81ac"),
		Yellow:        lipgloss.Color("#ebcb8b"),
		GreenLight:    lipgloss.Color("#a3be8c"),
		Green:         lipgloss.Color("#a3be8c"),
		GreenDark:     lipgloss.Color("#a3be8c"),
		Red:           lipgloss.Color("#bf616a"),
		RedDark:       lipgloss.Color("#bf616a"),
	},
	"Solarized Dark": {
		Name:          "Solarized Dark",
		Primary:       lipgloss.Color("#268bd2"),
		Secondary:     lipgloss.Color("#cb4b16"),
		Tertiary:      lipgloss.Color("#2aa198"),
		BgBase:        lipgloss.Color("#002b36"),
		BgBaseLighter: lipgloss.Color("#073642"),
		BgSubtle:      lipgloss.Color("#586e75"),
		BgOverlay:     lipgloss.Color("#657b83"),
		FgBase:        lipgloss.Color("#839496"),
		FgMuted:       lipgloss.Color("#93a1a1"),
		FgHalfMuted:   lipgloss.Color("#eee8d5"),
		FgSubtle:      lipgloss.Color("#586e75"),
		Border:        lipgloss.Color("#586e75"),
		BorderFocus:   lipgloss.Color("#268bd2"),
		Error:         lipgloss.Color("#dc322f"),
		Warning:       lipgloss.Color("#b58900"),
		Info:          lipgloss.Color("#268bd2"),
		White:         lipgloss.Color("#fdf6e3"),
		BlueLight:     lipgloss.Color("#268bd2"),
		Blue:          lipgloss.Color("#268bd2"),
		BlueDark:      lipgloss.Color("#268bd2"),
		Yellow:        lipgloss.Color("#b58900"),
		GreenLight:    lipgloss.Color("#859900"),
		Green:         lipgloss.Color("#859900"),
		GreenDark:     lipgloss.Color("#859900"),
		Red:           lipgloss.Color("#dc322f"),
		RedDark:       lipgloss.Color("#dc322f"),
	},
}

// GetTheme retrieves a theme by name, or falls back to "Default"
func GetTheme(name string) Theme {
	if t, ok := Themes[name]; ok {
		return t
	}
	return Themes["Default"]
}

// ThemeNames returns a sorted list of all available theme names.
func ThemeNames() []string {
	names := make([]string, 0, len(Themes))
	for k := range Themes {
		names = append(names, k)
	}
	sort.Strings(names)
	return names
}
