// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type File struct {
	ID        string
	SessionID string
	Path      string
	Content   string
	Version   int64
	CreatedAt int64
	UpdatedAt int64
}

type Message struct {
	ID               string
	SessionID        string
	Role             string
	Parts            string
	Model            sql.NullString
	CreatedAt        int64
	UpdatedAt        int64
	FinishedAt       sql.NullInt64
	Provider         sql.NullString
	IsSummaryMessage int64
}

type ReadFile struct {
	SessionID string
	Path      string
	ReadAt    int64
}

type Session struct {
	ID               string
	ParentSessionID  sql.NullString
	Title            string
	MessageCount     int64
	PromptTokens     int64
	CompletionTokens int64
	Cost             float64
	UpdatedAt        int64
	CreatedAt        int64
	SummaryMessageID sql.NullString
	Todos            sql.NullString
	Shared           int64
}
